package AuthenticationService.domain.enums;

public enum AuthorityName {
    READ_USER,
    VERIFICATION,
    EDIT_USER,
    CREATE_USER,
    CREATE_PRODUCT,
    READ_PRODUCT,
    EDIT_PRODUCT,
    MONEY_TRANSFER,
    SERVER,
    READ_ITEM,
    APPROVE_DOC,
    DEACTIVATE_USER,
    ADMIN_READ_PRODUCTS,
    ADMIN_READ_USERS,
    ADMIN_CREATE_ITEM,
    ADMIN_EDIT_ITEM,
    ADMIN_DEACTIVATE_ITEM,
    ACTIVATE_USER,
    ADMIN_EDIT_STATUS
}
